// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/epam/edp-argocd-operator/pkg/argoclient/models"
)

// ApplicationServiceWatchResourceTreeReader is a Reader for the ApplicationServiceWatchResourceTree structure.
type ApplicationServiceWatchResourceTreeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceWatchResourceTreeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceWatchResourceTreeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceWatchResourceTreeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceWatchResourceTreeOK creates a ApplicationServiceWatchResourceTreeOK with default headers values
func NewApplicationServiceWatchResourceTreeOK() *ApplicationServiceWatchResourceTreeOK {
	return &ApplicationServiceWatchResourceTreeOK{}
}

/* ApplicationServiceWatchResourceTreeOK describes a response with status code 200, with default header values.

A successful response.(streaming responses)
*/
type ApplicationServiceWatchResourceTreeOK struct {
	Payload *models.ApplicationServiceWatchResourceTreeOKBody
}

func (o *ApplicationServiceWatchResourceTreeOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/stream/applications/{applicationName}/resource-tree][%d] applicationServiceWatchResourceTreeOK  %+v", 200, o.Payload)
}
func (o *ApplicationServiceWatchResourceTreeOK) GetPayload() *models.ApplicationServiceWatchResourceTreeOKBody {
	return o.Payload
}

func (o *ApplicationServiceWatchResourceTreeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationServiceWatchResourceTreeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceWatchResourceTreeDefault creates a ApplicationServiceWatchResourceTreeDefault with default headers values
func NewApplicationServiceWatchResourceTreeDefault(code int) *ApplicationServiceWatchResourceTreeDefault {
	return &ApplicationServiceWatchResourceTreeDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceWatchResourceTreeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceWatchResourceTreeDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service watch resource tree default response
func (o *ApplicationServiceWatchResourceTreeDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServiceWatchResourceTreeDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/stream/applications/{applicationName}/resource-tree][%d] ApplicationService_WatchResourceTree default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServiceWatchResourceTreeDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceWatchResourceTreeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
