// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/epam/edp-argocd-operator/pkg/argoclient/models"
)

// ApplicationServiceWatchReader is a Reader for the ApplicationServiceWatch structure.
type ApplicationServiceWatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServiceWatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServiceWatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServiceWatchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServiceWatchOK creates a ApplicationServiceWatchOK with default headers values
func NewApplicationServiceWatchOK() *ApplicationServiceWatchOK {
	return &ApplicationServiceWatchOK{}
}

/* ApplicationServiceWatchOK describes a response with status code 200, with default header values.

A successful response.(streaming responses)
*/
type ApplicationServiceWatchOK struct {
	Payload *models.ApplicationServiceWatchOKBody
}

func (o *ApplicationServiceWatchOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/stream/applications][%d] applicationServiceWatchOK  %+v", 200, o.Payload)
}
func (o *ApplicationServiceWatchOK) GetPayload() *models.ApplicationServiceWatchOKBody {
	return o.Payload
}

func (o *ApplicationServiceWatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationServiceWatchOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServiceWatchDefault creates a ApplicationServiceWatchDefault with default headers values
func NewApplicationServiceWatchDefault(code int) *ApplicationServiceWatchDefault {
	return &ApplicationServiceWatchDefault{
		_statusCode: code,
	}
}

/* ApplicationServiceWatchDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServiceWatchDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service watch default response
func (o *ApplicationServiceWatchDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServiceWatchDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/stream/applications][%d] ApplicationService_Watch default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServiceWatchDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServiceWatchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
