// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/epam/edp-argocd-operator/pkg/argoclient/models"
)

// ApplicationServicePodLogsReader is a Reader for the ApplicationServicePodLogs structure.
type ApplicationServicePodLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationServicePodLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewApplicationServicePodLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewApplicationServicePodLogsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationServicePodLogsOK creates a ApplicationServicePodLogsOK with default headers values
func NewApplicationServicePodLogsOK() *ApplicationServicePodLogsOK {
	return &ApplicationServicePodLogsOK{}
}

/* ApplicationServicePodLogsOK describes a response with status code 200, with default header values.

A successful response.(streaming responses)
*/
type ApplicationServicePodLogsOK struct {
	Payload *models.ApplicationServicePodLogsOKBody
}

func (o *ApplicationServicePodLogsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/pods/{podName}/logs][%d] applicationServicePodLogsOK  %+v", 200, o.Payload)
}
func (o *ApplicationServicePodLogsOK) GetPayload() *models.ApplicationServicePodLogsOKBody {
	return o.Payload
}

func (o *ApplicationServicePodLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationServicePodLogsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewApplicationServicePodLogsDefault creates a ApplicationServicePodLogsDefault with default headers values
func NewApplicationServicePodLogsDefault(code int) *ApplicationServicePodLogsDefault {
	return &ApplicationServicePodLogsDefault{
		_statusCode: code,
	}
}

/* ApplicationServicePodLogsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ApplicationServicePodLogsDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the application service pod logs default response
func (o *ApplicationServicePodLogsDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationServicePodLogsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/pods/{podName}/logs][%d] ApplicationService_PodLogs default  %+v", o._statusCode, o.Payload)
}
func (o *ApplicationServicePodLogsDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *ApplicationServicePodLogsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
