# permissions for end users to edit argoapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argoapplication-editor-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - argoapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - argoapplications/status
  verbs:
  - get
