# permissions for end users to view argoapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argoapplication-viewer-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - argoapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - v1.edp.epam.com
  resources:
  - argoapplications/status
  verbs:
  - get
