apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  labels:
    argocd.edp.epam.com/secret-type: repository
stringData:
  type: git
  url: git@github.com:profile/some-repo.git
  project: default
#  Use insecure to work with privately hosted Git services over SSH.
#  If true, it is the same as use --insecure-skip-server-verification.
#  Optional, default - "false".
#  See: https://argo-cd.readthedocs.io/en/release-1.8/user-guide/private-repositories/#unknown-ssh-hosts
  insecure: "true"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    YOUR_PRIVATE_SSH_KEY
    -----END OPENSSH PRIVATE KEY-----
