apiVersion: v1.edp.epam.com/v1alpha1
kind: ArgoApplication
metadata:
  name: argoapplication-sample-helm
spec:
  project: default
  source:
    helm:
      parameters:
        - name: replicaCount
          value: "3"
    repoURL: git@github.com:profile/some-repo.git
    targetRevision: HEAD
    path: simple-app-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
