apiVersion: v1.edp.epam.com/v1alpha1
kind: ArgoApplication
metadata:
  name: argoapplication-sample
spec:
  project: default
  source:
    repoURL: git@github.com:argoproj/my-private-repo.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
