apiVersion: v2
description: A Helm chart for EDP Argo CD Operator
home: https://epam.github.io/edp-install/
name: edp-argocd-operator
type: application
version: 0.3.0
appVersion: 0.3.0
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - argocd
  - deployment
  - pipelines
  - helm
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-argocd-operator
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: edp-argocd-operator:0.2.0
      image: epamedp/edp-argocd-operator:0.2.0
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/crds: |
    - kind: ArgoApplication
      version: v1.edp.epam.com/v1alpha1
      name: argoapplication
      displayName: ArgoApplication
      description: ArgoApplication used in EDP platform
  artifacthub.io/crdsExamples: |
    - apiVersion: v1.edp.epam.com/v1alpha1
      kind: ArgoApplication
      metadata:
        name: argoapplication-sample-helm
      spec:
        project: default
        source:
          helm:
            parameters:
              - name: replicaCount
                value: "3"
          repoURL: git@github.com:profile/some-repo.git
          targetRevision: HEAD
          path: simple-app-chart
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
