# Default values for edp-argocd-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  # -- Docker repository name
  repository: epamedp/edp-argocd-operator
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  version: ""

# Configure External Secrets Operator to provision secrets for Platform and/or EDP
# https://external-secrets.io/latest/provider-aws-secrets-manager/
# See https://github.com/epam/edp-install/blob/master/deploy-templates/templates/external-secrets/secretstore.yaml for details
externalSecrets:
  # -- Enable External Secret Operator usage
  enabled: false
  # -- edp-install chart by default provision SecretStore with name `aws-parameterstore`
  secretStoreName: aws-parameterstore
  # -- Value name in AWS ParameterStore
  ssmParameterStoreName: /edp/deploy-secrets

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
