{{- if .Values.externalSecrets.enabled }}
{{- $awsSecretName := .Values.externalSecrets.ssmParameterStoreName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-access
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ required "An existing SecretStore name must be defined!" .Values.externalSecrets.secretStoreName }}
  data:
  - secretKey: auth-token
    remoteRef:
      key: {{ $awsSecretName }}
      property: edp-argocd-operator.token
  - secretKey: url
    remoteRef:
      key: {{ $awsSecretName }}
      property: edp-argocd-operator.url
{{- end }}
