apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "edp-argocd-operator.serviceAccountName" . }}-rolebinding
  labels:
    {{- include "edp-argocd-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "edp-argocd-operator.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "edp-argocd-operator.serviceAccountName" . }}
